version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cuong
      POSTGRES_PASSWORD: cuong
      POSTGRES_DB: payment
    volumes:
      - .:/code
  web:
    links:
      - postgres
    restart: always
    container_name: payment
    build:
      context: .
      dockerfile: Dockerfile
    image: django
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure

